import React from 'react';
import {
  MapPin, ArrowRight, Bus, Calendar, Hotel, Star, Phone, 
  ArrowLeft, Package, Filter, Tag, SearchX, Search, ArrowDownUp,
  Building, Plane, Clock, Users,DollarSign, ChevronLeft, ChevronRight,
  Wifi,Coffee,CheckCircle,User,Info,Car,Mail, ShieldCheck, Menu,
  X,Map, AtSign, Flag, UserCog, EyeOff, Eye, AlertCircle, Lock, InfoIcon,
  Trash2, ArrowUpRight, AlertTriangle,Settings,LogOut,Smartphone
} from 'lucide-react';

const icons = {
  location: <MapPin size={16} />,
  locationBig: <MapPin size={32} />,
  alertCircle: <AlertCircle size={24} />,
  eyeoff: <EyeOff size={16}/>,
  Eye: <Eye size={16}/>,
  Bigmap: <Map size={20}  color='#2563eb'/>,
  editUser: <UserCog size={16} />,
  BigeditUser: <UserCog size={20}  color='#2563eb'/>,
  map: <Map size={16} />,
  bus: <Bus size={16} />,
  at: <AtSign size={16}/>,
  calendar: <Calendar size={16} />,
  calendarMedium: <Calendar size={20} />,
  flag: <Flag size={16} />,
  password: <Lock size={16} />,
  Bpassword: <Lock size={20} color='#2563eb' />,
  hotel: <Hotel size={16} />,
  hotelMedium: <Hotel size={20} />,
  star: <Star size={14} className="pkg-star-yellow" />,
  arrow: <ArrowRight size={18} />,
  phone: <Phone size={16} />,
  backArrow: <ArrowLeft size={20} />,
  packageBanner: <Package size={36} />,
  sort: <ArrowDownUp size={22} />,
  building: <Building size={22} />,
  tag: <Tag size={22} />,
  search: <Search size={22} />,
  searchLarge: <Search size={40} />, // Para el estado vacío de transportes
  filterBadge: <Filter size={14} style={{ display: 'inline', marginRight: '6px', verticalAlign: 'middle' }} />,
  searchX: <SearchX size={40} />,
  planeButton: <Plane size={18} />,
  busButton: <Bus size={18} />,
  clock: <Clock size={18} />,
  users: <Users size={16}/>,
  userMedium: <User size={18}/>,
  smartphone: <Smartphone size={18}/>,
  smartphoneMedium: <Smartphone size={20}/>,
  Bsmartphone: <Smartphone size={20} color='#2563eb'/>,
  user: <User size={16}/>,
  dollar: <DollarSign size={16} />,
  chevronLeft: <ChevronLeft size={16}/>,
  ChevronRight: <ChevronRight size={16}/>,
  wifi: <Wifi size={16}/>,
  coffe: <Coffee size={16}/>,
  bus:<Bus size={16}/>,
  checkCircle: <CheckCircle size={16}/>,
  checkCircleMedium: <CheckCircle size={24}/>,
  info: <Info size={20}/>,
  car: <Car size={20}/>,
  email: <Mail size={20}/>,
  protected: <ShieldCheck size={20}/>,
  Bigprotected: <ShieldCheck size={20} color='#2563eb'/>,

  menu: <Menu size={20} />,
  close: <X size={20} />,
  closeMedium: <X size={24} />,
  info: <InfoIcon size={16}/>,
  infoMedium: <InfoIcon size={24}/>,
  trash: <Trash2 size={16}/>,
  trashMedium: <Trash2 size={24}/>,
  arowUpRight: <ArrowUpRight size={16}/>,
  arowUpRightMedium: <ArrowUpRight size={24}/>,
  alert: <AlertTriangle size={16}/>,
  alertMedium: <AlertTriangle size={24}/>,
  settings:<Settings size={16}/>,
  settingsMedium:<Settings size={18}/>,
  logout: <LogOut size={18}/>,
  logoutMedium: <LogOut size={18}/>


};

export default icons;